name: Build and publishto Docker Hub (手动)
on:
  workflow_dispatch:
    inputs:
      version:
        description: '版本号：'
        required: true
        default: '2.0.0'

jobs:
  build:
    name: build latest images for relase
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Push openvpn image to Docker Hub
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: wanrenzhizun/ovpn-admin
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: "openvpn-latest,openvpn-${{github.event.inputs.version}}"
          dockerfile: Dockerfile.openvpn

      - name: Push ovpn-admin image to Docker Hub
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: wanrenzhizun/ovpn-admin
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: "latest,${{github.event.inputs.version}}"
          dockerfile: Dockerfile
